name: login_signup
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  get: ^4.6.6
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1
  google_fonts: ^6.2.1
  velocity_x: ^4.2.1
  video_player: ^2.5.2
  chewie: ^1.3.0
  flutter_swiper_view: ^1.1.8
  audioplayers: ^6.1.0
  http: ^1.2.2
  chat_gpt_sdk: ^3.1.0
  flutter_gemini: ^2.0.5
  image_picker: ^1.1.2
  url_launcher: ^6.1.10
  mailer: ^6.1.2
  pdf: ^3.11.1
  printing: ^5.13.2
  pdf_image_renderer: ^1.0.0
  firebase_storage: ^12.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # ✅ Add this plugin for app icon generation
  flutter_launcher_icons: ^0.14.1

# ✅ App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_main.png"   # <-- place your logo image here
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
